lst_SRC_P = ['Production', 'Coal', 'Natural gas', 'Petroleum and other liquids', 'Nuclear, renewables, and other', 'Nuclear', 'Renewables']
lst_SRC_C = ['Consumption', 'Coal', 'Natural gas', 'Petroleum and other liquids', 'Nuclear, renewables, and other', 'Nuclear', 'Renewables']
ppetrol =['Venezuela', 'Arab Saudi', 'Canada', 'Iran', 'Iraq', 'Russia', 'Kuwait', 'United Arab Emirates', 'United States', 'Libia', 'Nigeria', 'Kazakhstan', 'China', 'Qatar']

North_America= ['Canada',
'Mexico',
'United States']


Cen_Sth_America =['Argentina',
'Bolivia',
'Brazil',
'Chile',
'Colombia',
'Cuba',
'Ecuador',
'Panama',
'Peru',
'Puerto Rico',
'Trinidad and Tobago',
'Venezuela',
'U.S. Virgin Islands']


Europe = ['Cyprus',
'Germany',
'Spain',
'Estonia',
'France',
'United Kingdom',
'Italy',
'Lithuania',
'Latvia',
'Netherlands',
'Norway',
'Poland',
'Romania',
'Turkey']
Eurasia = ['Azerbaijan', 
'Georgia',
'Kazakhstan',
'Moldova',
'Russia',
'Turkmenistan',
'Ukraine',
'Uzbekistan']


Africa =['Angola',
'Congo-Brazzaville',
'Algeria',
'Egypt',
'Gabon',
'Ghana',
'Equatorial Guinea',
'Kenya',
'Libya',
'Morocco',
'Mozambique',
'Nigeria',
'Sudan',
'South Sudan',
'Chad',
'Tunisia',
'Tanzania',
'Uganda',
'South Africa']


Middle_East = ['United Arab Emirates', 
'Bahrain',
'Iran',
'Iraq',
'Israel',
'Jordan',
'Kuwait',
'Lebanon',
'Oman',
'Palestinian Territories',
'Qatar',
'Saudi Arabia',
'Syria',
'Yemen']
Asia_Oceania = ['American Samoa',
'Australia',
'Bangladesh',
'Brunei',
'China',
'Guam',
'Indonesia',
'India',
'Japan',
'South Korea',
'Northern Mariana Islands',
'Malaysia',
'Pakistan',
'Philippines',
'North Korea',
'Singapore',
'Thailand',
'Taiwan',
'Vietnam']


todos = ['American Samoa',
'Australia',
'Bangladesh',
'Brunei',
'China',
'Guam',
'Indonesia',
'India',
'Japan',
'South Korea',
'Northern Mariana Islands',
'Malaysia',
'Pakistan',
'Philippines',
'North Korea',
'Singapore',
'Thailand',
'Taiwan',
'Vietnam',
'Canada',
'Mexico',
'United States',
'Argentina',
'Bolivia',
'Brazil',
'Chile',
'Colombia',
'Cuba',
'Ecuador',
'Panama',
'Peru',
'Puerto Rico',
'Trinidad and Tobago',
'Venezuela',
'U.S. Virgin Islands',
'Cyprus',
'Germany',
'Spain',
'Estonia',
'France',
'United Kingdom',
'Italy',
'Lithuania',
'Latvia',
'Netherlands',
'Norway',
'Poland',
'Romania',
'Turkey',
'Azerbaijan', 
'Georgia',
'Kazakhstan',
'Moldova',
'Russia',
'Turkmenistan',
'Ukraine',
'Uzbekistan',
'Angola',
'Congo-Brazzaville',
'Algeria',
'Egypt',
'Gabon',
'Ghana',
'Equatorial Guinea',
'Kenya',
'Libya',
'Morocco',
'Mozambique',
'Nigeria',
'Sudan',
'South Sudan',
'Chad',
'Tunisia',
'Tanzania',
'Uganda',
'South Africa']


